services:
  db-property-basedtesting:
    hostname: db.property.basedtesting.local
    container_name: db.property.basedtesting.local
    image: postgres:15.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '36000:5432'
    volumes: 
      - db-property-basedtesting:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-property-based-testing:
    hostname: backend.signature.project_management.local
    container_name: backend.signature.project_management.local
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      db-signature-project-management:  
        condition: service_healthy
    environment:
      DB_HOST: db-property-basedtesting  
      DB_PORT: 5432
      DB_NAME: property_basedtesting 
      JWT_SECRET: 'secreto'
      APP_ENV: staging
    ports:
      - "37000:3000"

volumes:
  db-signature-project-management:  
    driver: local

