services:
  db-property-based-testing:
    hostname: db.property.basedtesting.local
    container_name: db.property.basedtesting.local
    image: postgres:15.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '36000:5432'
    volumes: 
      - db-property-based-testing:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-property-based-testing:
    hostname: backend.property.project_management.local
    container_name: backend.property.project_management.local
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      db-property-based-testing:  
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-property-based-testing:5432/property_basedtesting 
      APP_ENV: staging
    ports:
      - "37000:3000"

volumes:
  db-property-based-testing:  
    driver: local

